### ISSUE TITLE
solr.cfg points to nonexistent URL

### ISSUE THREAD

**Issue by dthomas218** [Jarn/collective.solr#21]
The instructions at https://pypi.python.org/pypi/collective.solr/3.1 show an extends:
https://github.com/Jarn/collective.solr/raw/master/buildout/solr.cfg
but this contains a nonexistent URL:
http://mirror.softaculous.com/apache/lucene/solr/3.6.0/apache-solr-3.6.0.tgz
The mirror does have a version 3.6.2, and two 4.x versions as well.

The error is not very helpful: 
IOError: ('http error', 404, 'Not Found', <httplib.HTTPMessage instance at 0x9c9ab0c>)

Can the extends file be updated?

**Comment by tkimnguyen** [comment]
In case you hadn't thought of it, you can visit the page https://github.com/Jarn/collective.solr/raw/master/buildout/solr.cfg and save it locally, in my case to a file named "modified_jarn_solr.cfg", and then in my solr.cfg instead of extending the original URL I extend the new file.

Then in the new file if I change the line

collective.recipe.solrinstance = 3.6

to

collective.recipe.solrinstance = 3.8

and change the line

url = http://mirror.softaculous.com/apache/lucene/solr/3.6.0/apache-solr-3.6.0.tgz

to

url = http://archive.apache.org/dist/lucene/solr/3.6.0/apache-solr-3.6.0.tgz

it seems to build ok.

**Comment by dthomas218** [comment]
Thanks, Kim! It installed successfully.

Dan

**Comment by witsch** [comment]
ftr, this was now also (finally) cleaned up in ffd5439931cce62555bf8342cd8e8536ba7ff702
